#!/usr/bin/env bash
set -euo pipefail

# Safe helper to enable real firewall enforcement on a test device.
# This performs prechecks and writes a local env file in deploy/pi/

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
HEALTH_URL="${HEALTH_URL:-http://127.0.0.1:9000/api/health}"
FAIL_THRESHOLD=3

usage() {
  cat <<EOF
Usage: $0 [--apply]

Runs health and test prechecks. With --apply it will create
deploy/pi/firewall-rollback.env (local) with enforcement enabled
and ENABLE_ROLLBACK_GUARD=1. You must copy that file to
/etc/sentinel/firewall-rollback.env on the target Pi and enable the timer.
EOF
}

if [ "${1-}" = "-h" ] || [ "${1-}" = "--help" ]; then
  usage
  exit 0
fi

echo "1) Health check against $HEALTH_URL"
if curl -fsS --max-time 3 "$HEALTH_URL" >/dev/null; then
  echo "  OK"
else
  echo "  FAILED: dashboard health endpoint not responding" >&2
  exit 2
fi

echo "2) Running privileged container firewall integration tests (requires sudo + docker)"
export SENTINEL_RUN_FIREWALL_CONTAINER_TESTS=1
if sudo -E bash -c "cd '$REPO_DIR' && pytest -q tests/test_firewall_container_integration.py"; then
  echo "  Integration tests passed"
else
  echo "  Integration tests failed; aborting" >&2
  exit 3
fi

if [ "${1-}" != "--apply" ]; then
  echo "Prechecks passed. Rerun with --apply to write deploy/pi/firewall-rollback.env with enforcement enabled."
  exit 0
fi

OUT="$REPO_DIR/deploy/pi/firewall-rollback.env"
cat > "$OUT" <<EOF
# Local env for rollback guard (generated by scripts/enable_firewall_enforcement.sh)
ENABLE_ROLLBACK_GUARD=1
REPO_DIR=$REPO_DIR
VENV_PYTHON=${VENV_PYTHON:-$REPO_DIR/venv/bin/python}
HEALTH_URL=$HEALTH_URL
FAIL_THRESHOLD=$FAIL_THRESHOLD
# When ready, copy this file to /etc/sentinel/firewall-rollback.env on the Pi
# and enable the timer: sudo cp $OUT /etc/sentinel/firewall-rollback.env && sudo systemctl enable --now sentinel-firewall-rollback-guard.timer
EOF

echo "Wrote $OUT. Review, then copy to /etc/sentinel/firewall-rollback.env on the Pi to enable the guard and timer."
